# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageMixer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(923, 667)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 78, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 65, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 34, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 78, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 65, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 34, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 78, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 65, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 34, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.img1Layout = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1Layout.sizePolicy().hasHeightForWidth())
        self.img1Layout.setSizePolicy(sizePolicy)
        self.img1Layout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img1Layout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img1Layout.setObjectName("img1Layout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.img1Layout)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img1Label = QtWidgets.QLabel(self.img1Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1Label.sizePolicy().hasHeightForWidth())
        self.img1Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.img1Label.setFont(font)
        self.img1Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.img1Label.setObjectName("img1Label")
        self.horizontalLayout_2.addWidget(self.img1Label)
        self.img1ComboBox = QtWidgets.QComboBox(self.img1Layout)
        self.img1ComboBox.setEnabled(False)
        self.img1ComboBox.setObjectName("img1ComboBox")
        self.img1ComboBox.addItem("")
        self.img1ComboBox.addItem("")
        self.img1ComboBox.addItem("")
        self.img1ComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.img1ComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.img1line = QtWidgets.QFrame(self.img1Layout)
        self.img1line.setFrameShape(QtWidgets.QFrame.HLine)
        self.img1line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.img1line.setObjectName("img1line")
        self.verticalLayout_4.addWidget(self.img1line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.img1OriginalBox = QtWidgets.QGroupBox(self.img1Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img1OriginalBox.sizePolicy().hasHeightForWidth())
        self.img1OriginalBox.setSizePolicy(sizePolicy)
        self.img1OriginalBox.setFlat(True)
        self.img1OriginalBox.setObjectName("img1OriginalBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.img1OriginalBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img1Original = ImageView(self.img1OriginalBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img1Original.sizePolicy().hasHeightForWidth())
        self.img1Original.setSizePolicy(sizePolicy)
        self.img1Original.setObjectName("img1Original")
        self.horizontalLayout_5.addWidget(self.img1Original)
        self.horizontalLayout_7.addWidget(self.img1OriginalBox)
        self.img1ComponentBox = QtWidgets.QGroupBox(self.img1Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img1ComponentBox.sizePolicy().hasHeightForWidth())
        self.img1ComponentBox.setSizePolicy(sizePolicy)
        self.img1ComponentBox.setFlat(False)
        self.img1ComponentBox.setObjectName("img1ComponentBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.img1ComponentBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.img1Component = ImageView(self.img1ComponentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img1Component.sizePolicy().hasHeightForWidth())
        self.img1Component.setSizePolicy(sizePolicy)
        self.img1Component.setObjectName("img1Component")
        self.horizontalLayout_6.addWidget(self.img1Component)
        self.horizontalLayout_7.addWidget(self.img1ComponentBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.img1Layout, 0, 0, 1, 1)
        self.mixerLayout = QtWidgets.QFrame(self.centralwidget)
        self.mixerLayout.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mixerLayout.sizePolicy().hasHeightForWidth())
        self.mixerLayout.setSizePolicy(sizePolicy)
        self.mixerLayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mixerLayout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mixerLayout.setObjectName("mixerLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mixerLayout)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.mixerlabel = QtWidgets.QLabel(self.mixerLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mixerlabel.sizePolicy().hasHeightForWidth())
        self.mixerlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mixerlabel.setFont(font)
        self.mixerlabel.setObjectName("mixerlabel")
        self.horizontalLayout_10.addWidget(self.mixerlabel)
        self.outputComboBox = QtWidgets.QComboBox(self.mixerLayout)
        self.outputComboBox.setObjectName("outputComboBox")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.outputComboBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.mixerLine = QtWidgets.QFrame(self.mixerLayout)
        self.mixerLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.mixerLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mixerLine.setObjectName("mixerLine")
        self.verticalLayout_7.addWidget(self.mixerLine)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.comp1label = QtWidgets.QLabel(self.mixerLayout)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.comp1label.setFont(font)
        self.comp1label.setObjectName("comp1label")
        self.horizontalLayout_12.addWidget(self.comp1label)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comp1CompoBox = QtWidgets.QComboBox(self.mixerLayout)
        self.comp1CompoBox.setObjectName("comp1CompoBox")
        self.comp1CompoBox.addItem("")
        self.comp1CompoBox.addItem("")
        self.horizontalLayout_11.addWidget(self.comp1CompoBox)
        self.comp1HorizontalSlider = QtWidgets.QSlider(self.mixerLayout)
        self.comp1HorizontalSlider.setMinimum(0)
        self.comp1HorizontalSlider.setMaximum(100)
        self.comp1HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.comp1HorizontalSlider.setObjectName("comp1HorizontalSlider")
        self.horizontalLayout_11.addWidget(self.comp1HorizontalSlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.comp1ChoiceComboBox = QtWidgets.QComboBox(self.mixerLayout)
        self.comp1ChoiceComboBox.setObjectName("comp1ChoiceComboBox")
        self.comp1ChoiceComboBox.addItem("")
        self.comp1ChoiceComboBox.addItem("")
        self.comp1ChoiceComboBox.addItem("")
        self.comp1ChoiceComboBox.addItem("")
        self.comp1ChoiceComboBox.addItem("")
        self.comp1ChoiceComboBox.addItem("")
        self.verticalLayout_5.addWidget(self.comp1ChoiceComboBox)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comp2label = QtWidgets.QLabel(self.mixerLayout)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comp2label.setFont(font)
        self.comp2label.setObjectName("comp2label")
        self.horizontalLayout_14.addWidget(self.comp2label)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.comp2CompoBox = QtWidgets.QComboBox(self.mixerLayout)
        self.comp2CompoBox.setObjectName("comp2CompoBox")
        self.comp2CompoBox.addItem("")
        self.comp2CompoBox.addItem("")
        self.horizontalLayout_13.addWidget(self.comp2CompoBox)
        self.comp2HorizontalSlider = QtWidgets.QSlider(self.mixerLayout)
        self.comp2HorizontalSlider.setMinimum(0)
        self.comp2HorizontalSlider.setMaximum(100)
        self.comp2HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.comp2HorizontalSlider.setObjectName("comp2HorizontalSlider")
        self.horizontalLayout_13.addWidget(self.comp2HorizontalSlider)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.comp2ChoiceComboBox = QtWidgets.QComboBox(self.mixerLayout)
        self.comp2ChoiceComboBox.setObjectName("comp2ChoiceComboBox")
        self.comp2ChoiceComboBox.addItem("")
        self.comp2ChoiceComboBox.addItem("")
        self.comp2ChoiceComboBox.addItem("")
        self.comp2ChoiceComboBox.addItem("")
        self.comp2ChoiceComboBox.addItem("")
        self.comp2ChoiceComboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comp2ChoiceComboBox)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.gridLayout.addWidget(self.mixerLayout, 0, 1, 1, 1)
        self.img2Layout = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img2Layout.sizePolicy().hasHeightForWidth())
        self.img2Layout.setSizePolicy(sizePolicy)
        self.img2Layout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img2Layout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img2Layout.setObjectName("img2Layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.img2Layout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img2Label = QtWidgets.QLabel(self.img2Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img2Label.sizePolicy().hasHeightForWidth())
        self.img2Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.img2Label.setFont(font)
        self.img2Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.img2Label.setObjectName("img2Label")
        self.horizontalLayout_3.addWidget(self.img2Label)
        self.img2ComboBox = QtWidgets.QComboBox(self.img2Layout)
        self.img2ComboBox.setEnabled(False)
        self.img2ComboBox.setObjectName("img2ComboBox")
        self.img2ComboBox.addItem("")
        self.img2ComboBox.addItem("")
        self.img2ComboBox.addItem("")
        self.img2ComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.img2ComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.img2line = QtWidgets.QFrame(self.img2Layout)
        self.img2line.setFrameShape(QtWidgets.QFrame.HLine)
        self.img2line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.img2line.setObjectName("img2line")
        self.verticalLayout_3.addWidget(self.img2line)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.img2OriginalBox = QtWidgets.QGroupBox(self.img2Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img2OriginalBox.sizePolicy().hasHeightForWidth())
        self.img2OriginalBox.setSizePolicy(sizePolicy)
        self.img2OriginalBox.setAutoFillBackground(False)
        self.img2OriginalBox.setFlat(True)
        self.img2OriginalBox.setObjectName("img2OriginalBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.img2OriginalBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.img2Original = ImageView(self.img2OriginalBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img2Original.sizePolicy().hasHeightForWidth())
        self.img2Original.setSizePolicy(sizePolicy)
        self.img2Original.setObjectName("img2Original")
        self.horizontalLayout_8.addWidget(self.img2Original)
        self.horizontalLayout_9.addWidget(self.img2OriginalBox)
        self.img2ComponentBox = QtWidgets.QGroupBox(self.img2Layout)
        self.img2ComponentBox.setFlat(True)
        self.img2ComponentBox.setObjectName("img2ComponentBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.img2ComponentBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.img2Component = ImageView(self.img2ComponentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img2Component.sizePolicy().hasHeightForWidth())
        self.img2Component.setSizePolicy(sizePolicy)
        self.img2Component.setObjectName("img2Component")
        self.horizontalLayout_4.addWidget(self.img2Component)
        self.horizontalLayout_9.addWidget(self.img2ComponentBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout.addWidget(self.img2Layout, 1, 0, 1, 1)
        self.outputLayout = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLayout.sizePolicy().hasHeightForWidth())
        self.outputLayout.setSizePolicy(sizePolicy)
        self.outputLayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputLayout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLayout.setObjectName("outputLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.outputLayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.op1label = QtWidgets.QLabel(self.outputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.op1label.sizePolicy().hasHeightForWidth())
        self.op1label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.op1label.setFont(font)
        self.op1label.setMouseTracking(False)
        self.op1label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.op1label.setTextFormat(QtCore.Qt.AutoText)
        self.op1label.setScaledContents(False)
        self.op1label.setAlignment(QtCore.Qt.AlignCenter)
        self.op1label.setWordWrap(False)
        self.op1label.setObjectName("op1label")
        self.verticalLayout.addWidget(self.op1label)
        self.output1Img = ImageView(self.outputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.output1Img.sizePolicy().hasHeightForWidth())
        self.output1Img.setSizePolicy(sizePolicy)
        self.output1Img.setObjectName("output1Img")
        self.verticalLayout.addWidget(self.output1Img)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.op2label_2 = QtWidgets.QLabel(self.outputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.op2label_2.sizePolicy().hasHeightForWidth())
        self.op2label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.op2label_2.setFont(font)
        self.op2label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.op2label_2.setObjectName("op2label_2")
        self.verticalLayout_2.addWidget(self.op2label_2)
        self.output2Img = ImageView(self.outputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.output2Img.sizePolicy().hasHeightForWidth())
        self.output2Img.setSizePolicy(sizePolicy)
        self.output2Img.setObjectName("output2Img")
        self.verticalLayout_2.addWidget(self.output2Img)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.outputLayout, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 22))
        self.menubar.setObjectName("menubar")
        self.menuLoad = QtWidgets.QMenu(self.menubar)
        self.menuLoad.setObjectName("menuLoad")
        MainWindow.setMenuBar(self.menubar)
        self.actionLoadImage1 = QtWidgets.QAction(MainWindow)
        self.actionLoadImage1.setObjectName("actionLoadImage1")
        self.actionLoadImage2 = QtWidgets.QAction(MainWindow)
        self.actionLoadImage2.setObjectName("actionLoadImage2")
        self.menuLoad.addAction(self.actionLoadImage1)
        self.menuLoad.addAction(self.actionLoadImage2)
        self.menubar.addAction(self.menuLoad.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img1Label.setText(_translate("MainWindow", "Image 1"))
        self.img1ComboBox.setItemText(0, _translate("MainWindow", "FT Magnitude"))
        self.img1ComboBox.setItemText(1, _translate("MainWindow", "FT Phase"))
        self.img1ComboBox.setItemText(2, _translate("MainWindow", "FT Real component"))
        self.img1ComboBox.setItemText(3, _translate("MainWindow", "FT Imaginary component"))
        self.img1OriginalBox.setTitle(_translate("MainWindow", "Original Image"))
        self.img1ComponentBox.setTitle(_translate("MainWindow", "Result"))
        self.mixerlabel.setText(_translate("MainWindow", "Mixer Output to : "))
        self.outputComboBox.setItemText(0, _translate("MainWindow", "Output 1"))
        self.outputComboBox.setItemText(1, _translate("MainWindow", "Output 2"))
        self.comp1label.setText(_translate("MainWindow", "Component 1:"))
        self.comp1CompoBox.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comp1CompoBox.setItemText(1, _translate("MainWindow", "Image 2"))
        self.comp1ChoiceComboBox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comp1ChoiceComboBox.setItemText(1, _translate("MainWindow", "Phase"))
        self.comp1ChoiceComboBox.setItemText(2, _translate("MainWindow", "Real component"))
        self.comp1ChoiceComboBox.setItemText(3, _translate("MainWindow", "Imaginary component"))
        self.comp1ChoiceComboBox.setItemText(4, _translate("MainWindow", "Uniform magnitude"))
        self.comp1ChoiceComboBox.setItemText(5, _translate("MainWindow", "Uniform phase"))
        self.comp2label.setText(_translate("MainWindow", "Component 2:"))
        self.comp2CompoBox.setItemText(0, _translate("MainWindow", "Image 1"))
        self.comp2CompoBox.setItemText(1, _translate("MainWindow", "Image 2"))
        self.comp2ChoiceComboBox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comp2ChoiceComboBox.setItemText(1, _translate("MainWindow", "Phase"))
        self.comp2ChoiceComboBox.setItemText(2, _translate("MainWindow", "Real component"))
        self.comp2ChoiceComboBox.setItemText(3, _translate("MainWindow", "Imaginary component"))
        self.comp2ChoiceComboBox.setItemText(4, _translate("MainWindow", "Uniform magnitude"))
        self.comp2ChoiceComboBox.setItemText(5, _translate("MainWindow", "Uniform phase"))
        self.img2Label.setText(_translate("MainWindow", "Image 2"))
        self.img2ComboBox.setItemText(0, _translate("MainWindow", "FT Magnitude"))
        self.img2ComboBox.setItemText(1, _translate("MainWindow", "FT Phase"))
        self.img2ComboBox.setItemText(2, _translate("MainWindow", "FT Real component"))
        self.img2ComboBox.setItemText(3, _translate("MainWindow", "FT Imaginary component"))
        self.img2OriginalBox.setTitle(_translate("MainWindow", "Original Image"))
        self.img2ComponentBox.setTitle(_translate("MainWindow", "Result"))
        self.op1label.setText(_translate("MainWindow", "Output 1"))
        self.op2label_2.setText(_translate("MainWindow", "Output 2"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.actionLoadImage1.setText(_translate("MainWindow", "Image 1"))
        self.actionLoadImage2.setText(_translate("MainWindow", "Image 2"))
from pyqtgraph import ImageView
